<?php

namespace webloja\DCPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ControleFisicoStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleFisicoStatusRepository extends EntityRepository
{
}
