<?php

namespace webloja\DCPBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ControleFisicoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \webloja\DCPBundle\Controller\ControleFisicoController();
        return $instance;
    }
}
