<?php

namespace webloja\ChamadosBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ChamadosController__JMSInjector
{
    public static function inject($container) {
        $instance = new \webloja\ChamadosBundle\Controller\ChamadosController();
        return $instance;
    }
}
