parameters:
    database_driver:   pdo_mysql
    database_host:     52.31.153.101
    database_port:     3308
    database_name:     lasasap
    database_user:     fmello
    database_password: fmello

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
