Ocorrencia:
    pattern:  /Ocorrencia/{id_interno}
    defaults: { _controller: ChamadosBundle:Chamados:index }
    
select_modulos:
    pattern:  /Modulos
    defaults: { _controller: ChamadosBundle:Chamados:modulo }
    
select_links:
    pattern:  /Links
    defaults: { _controller: ChamadosBundle:Chamados:link }

OcorrenciaListar:
    pattern:  /    