DCPCriarControleFisico9000:
    pattern:  /DCP/Criar/Controle/Fisico/9000/{id_interno}
    defaults: { _controller: DCPBundle:ControleFisico:indexControleFisico9000 }

ValidaSAPControleFisico9000:
    pattern:  /DCP/Valida/SAP/Controle/Fisico/9000
    defaults: { _controller: DCPBundle:ControleFisico:validaSap }
