<?php

namespace webloja\DOLBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TrackAbastecimentoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \webloja\DOLBundle\Controller\TrackAbastecimentoController();
        return $instance;
    }
}
