<?php

namespace webloja\weblojaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FornecedorController__JMSInjector
{
    public static function inject($container) {
        $instance = new \webloja\weblojaBundle\Controller\FornecedorController();
        return $instance;
    }
}
