parameters:
#    merchen.example.class: webloja\MerchanBundle\Example

services:
#    merchen.example:
#        class: %merchen.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
