login:
    pattern:  /webloja
    defaults: { _controller: WeblojaBundle:Login:index }
    
principal:
    pattern:  /home
    defaults: { _controller: WeblojaBundle:Home:index }
       
logout:
    pattern:  /logout
    defaults: { _controller: WeblojaBundle:Home:logout }
    
root:
    path:   /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route:    principal

webloja_menu_interno:
    pattern:  /menu/principal/criar
    defaults: { _controller: WeblojaBundle:Menu:criarMenuInterno }