parameters:
#    webloja.example.class: webloja\weblojaBundle\Example

services:
#    webloja.example:
#        class: %webloja.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
